main:
  api-level: API14
  labels: [ API14 ]
  tizen-branch: tizen
  version-prefix: 14.0.0

API13:
  api-level: API13
  labels: [ API13 ]
  tizen-branch: tizen_10.0
  version-prefix: 13.0.0

API12:
  api-level: API12
  labels: [ API12 ]
  tizen-branch: tizen_9.0
  version-prefix: 12.0.0

API11:
  api-level: API11
  labels: [ API11 ]
  tizen-branch: tizen_8.0
  version-prefix: 11.0.0

API10:
  api-level: API10
  labels: [ API10 ]
  tizen-branch: tizen_7.0
  version-prefix: 10.0.0

API9:
  api-level: API9
  labels: [ API9 ]
  tizen-branch: tizen_6.5
  version-prefix: 9.0.0

API8:
  api-level: API8
  labels: [ API8 ]
  tizen-branch: tizen_6.0
  version-prefix: 8.0.0

API7:
  api-level: API7
  labels: [ API7 ]
  tizen-branch: tizen_5.5
  version-prefix: 7.0.0

API6:
  api-level: API6
  labels: [ API6 ]
  tizen-branch: tizen_5.5_tv
  version-prefix: 6.0.0

API5:
  api-level: API5
  labels: [ API5 ]
  tizen-branch: tizen_5.0
  version-prefix: 5.0.0

API4:
  api-level: API4
  labels: [ API4 ]
  tizen-branch: tizen_4.0
  version-prefix: 4.0.1

DevelNUI:
  labels: [ Devel-NUI ]
