//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.9
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NUI {

public enum DimensionType {
  WIDTH = 0x1,
  HEIGHT = 0x2,
  ALL_DIMENSIONS = 0x3
}

}
