//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.9
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

namespace Tizen.NUI
{
    [Obsolete("Please do not use! this will be internal")]
    public class SWIGTYPE_p_CallbackBase
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;

        internal SWIGTYPE_p_CallbackBase(global::System.IntPtr cPtr, bool futureUse)
        {
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        protected SWIGTYPE_p_CallbackBase()
        {
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SWIGTYPE_p_CallbackBase obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }
    }

}
