/*
 * Copyright(c) 2021 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// This File has been auto-generated by SWIG and then modified using DALi Ruby Scripts
// Some have been manually changed
// friend assembly setting
// compile with: /target:Tizen.NUI.ExtTEST /keyfile:FriendAssemblies.snk

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Tizen.Multimedia, " + Tizen.NUI.PublicKey.TizenFX)]
[assembly: InternalsVisibleTo("Tizen.NUI.Wearable, " + Tizen.NUI.PublicKey.TizenFX)]
[assembly: InternalsVisibleTo("Tizen.NUI.Components, " + Tizen.NUI.PublicKey.TizenFX)]

[assembly: InternalsVisibleTo("Tizen.TV.NUI, " + Tizen.NUI.PublicKey.TizenTV)]
[assembly: InternalsVisibleTo("Tizen.TV.NUI.Component, " + Tizen.NUI.PublicKey.TizenTV)]

[assembly: InternalsVisibleTo("Tizen.TV.FLUX, " + Tizen.NUI.PublicKey.TizenTV)]
[assembly: InternalsVisibleTo("Tizen.TV.FLUX.Component, " + Tizen.NUI.PublicKey.TizenTV)]
[assembly: InternalsVisibleTo("Tizen.TV.FLUX.Example, " + Tizen.NUI.PublicKey.TizenTV)]
[assembly: InternalsVisibleTo("Tizen.TV.NUI.Example, " + Tizen.NUI.PublicKey.TizenTV)]

[assembly: InternalsVisibleTo("NuiSample, " + Tizen.NUI.PublicKey.Sample)]
[assembly: InternalsVisibleTo("Tizen.NUI.Devel.Tests, " + Tizen.NUI.PublicKey.Sample)]

namespace Tizen.NUI
{
    internal static class PublicKey
    {
        internal const string TizenFX =
            "PublicKey=0024000004800000940000000602000000240000525341310004000001000100d115b100424841" +
            "6b12d21b626cfb17149c9303fe394693fd3b32d7872e89559a4fa96c98110c2e62eea48aca693b" +
            "ddbe17094ca8ea2e2cd79970ca590fb672b9b371b5d7002076817321f62d6483ea50c56dbd1f37" +
            "b185a4c24c47718876e6ae6d266508c551170d4cbdda3f82edaff9405ee3d7857282d8269e8e518d2f0fb2";

        internal const string TizenTV =
            "PublicKey=0024000004800000940000000602000000240000525341310004000001000100ed445c2a988d35b" +
            "99e5766f42eef33d89d1f67225db051f011abcfce47a4788875c39750a2e5695f1ec117f41d96610419811762" +
            "669f98131db30a6e64c6bb8fde3731f373f6cda4c0087d121f5108559f216dc015807dc46ec5a4d1b63f5deff" +
            "64c01754a0db0dc849bc300672572cbd2697432ab6c193ebf9fade6bf0f2aad";

        internal const string Sample =
            "PublicKey=0024000004800000940000000602000000240000525341310004000001000100a5bcf6fb6095141f" +
            "a8146ec74d5b0be8b09a063f8f1f32604b10df6e498788182840bd15c93ba1a5c0b9aeee8fe2be42ea9c0b5fe32" +
            "e1d6d5602b2a4fa813114fd58c4b2910d93e5181b90925458b4b8b003c30d97830a17ad90a92f34f60a11f67a78757" +
            "e6b2035e799be5ab69a41ede17cad2e2b7967fbf49b685452496be0";

    }
}
