/*
 * Copyright (c) 2016 Samsung Electronics Co., Ltd All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace ElmSharp.Accessible
{
    public enum AccessRole
    {
        Invalid,
        AcceleratorLabel,
        Alert,
        Animation,
        Arrow,
        Calendar,
        Canvas,
        CheckBox,
        CheckMenuItem,
        ColorChooser,
        ColumnHeader,
        ComboBox,
        DateEditor,
        DesktopIcon,
        DesktopFrame,
        Dial,
        Dialog,
        DirectoryPane,
        DrawingArea,
        FileChooser,
        Filler,
        FocusTraversable,
        FontChooser,
        Frame,
        GlassPane,
        HtmlContainer,
        Icon,
        Image,
        InternalFrame,
        Label,
        LayeredPane,
        List,
        ListItem,
        Menu,
        MenuBar,
        MenuItem,
        OptionPane,
        PageTab,
        PageTabList,
        Panel,
        PasswordText,
        PopupMenu,
        ProgressBar,
        PushButton,
        RadioButton,
        RadioMenuItem,
        RootPane,
        RowHeader,
        ScrollBar,
        ScrollPane,
        Separator,
        Slider,
        SpinButton,
        SplitPane,
        StatusBar,
        Table,
        TableCell,
        TableColumnHeader,
        TableRowHeader,
        TearoffMenuItem,
        Terminal,
        Text,
        ToggleButton,
        ToolBar,
        ToolTip,
        Tree,
        TreeTable,
        Unknown,
        Viewport,
        Window,
        Extended,
        Header,
        Footer,
        Paragraph,
        Ruler,
        Application,
        Autocomplete,
        Editbar,
        Embedded,
        Entry,
        Chart,
        Caption,
        DocumentFrame,
        Heading,
        Page,
        Section,
        RedundantObject,
        Form,
        Link,
        InputMethodWindow,
        TableRow,
        TreeItem,
        DocumentSpreadsheet,
        DocumentPresentation,
        DocumentText,
        DocumentWeb,
        DocumentEmail,
        Comment,
        ListBox,
        Grouping,
        ImageMap,
        Notification,
        InfoBar
    }
}
