//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.9
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/* moved to VisualMaps.cs 
namespace Tizen.NUI {

public enum VisualTransformPropertyType {
  OFFSET,
  SIZE,
  ORIGIN,
  ANCHOR_POINT,
  OFFSET_POLICY,
  SIZE_POLICY
}

}
*/