#pragma warning disable CS1591
using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.ComponentModel;
namespace UIKit {

namespace Input {

/// <summary>Event data sent when inputs are put on hold or resumed.</summary>
[UIKit.Input.Hold.NativeMethods]
[UIKit.Wrapper.BindingEntity]
public class Hold : UIKit.Object, UIKit.Input.IEvent
{
    /// <summary>Pointer to the native class description.</summary>
    public override System.IntPtr NativeClass
    {
        get
        {
            if (((object)this).GetType() == typeof(Hold))
            {
                return GetUIKitClassStatic();
            }
            else
            {
                return UIKit.Wrapper.ClassRegister.klassFromType[((object)this).GetType()];
            }
        }
    }

    [System.Runtime.InteropServices.DllImport(UIKit.Libs.Evas)] internal static extern System.IntPtr
        efl_input_hold_class_get();

    /// <summary>Initializes a new instance of the <see cref="Hold"/> class.</summary>
    /// <param name="parent">Parent instance.</param>
    /// <since_tizen> 6 </since_tizen>
    public Hold(UIKit.Object parent= null
            ) : base(efl_input_hold_class_get(), parent)
    {
        FinishInstantiation();
    }

    /// <summary>Subclasses should override this constructor if they are expected to be instantiated from native code.
    /// Do not call this constructor directly.</summary>
    /// <param name="ch">Tag struct storing the native handle of the object being constructed.</param>
    /// <since_tizen> 6 </since_tizen>
    protected Hold(ConstructingHandle ch) : base(ch)
    {
    }

    /// <summary>Initializes a new instance of the <see cref="Hold"/> class.
    /// Internal usage: Constructs an instance from a native pointer. This is used when interacting with C code and should not be used directly.</summary>
    /// <param name="wh">The native pointer to be wrapped.</param>
    /// <since_tizen> 6 </since_tizen>
    protected Hold(UIKit.Wrapper.Globals.WrappingHandle wh) : base(wh)
    {
    }

    /// <summary>Initializes a new instance of the <see cref="Hold"/> class.
    /// Internal usage: Constructor to forward the wrapper initialization to the root class that interfaces with native code. Should not be used directly.</summary>
    /// <param name="baseKlass">The pointer to the base native Eo class.</param>
    /// <param name="parent">The UIKit.Object parent of this instance.</param>
    protected Hold(IntPtr baseKlass, UIKit.Object parent) : base(baseKlass, parent)
    {
    }


    /// <summary>Property to show if inputs are now on hold.</summary>
    /// <returns><c>true</c> if inputs are on hold, <c>false</c> otherwise</returns>
    public virtual bool GetInputHold() {
        var _ret_var = UIKit.Input.Hold.NativeMethods.efl_input_hold_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary>Property to show if inputs are now on hold.</summary>
    /// <param name="val"><c>true</c> if inputs are on hold, <c>false</c> otherwise</param>
    public virtual void SetInputHold(bool val) {
        UIKit.Input.Hold.NativeMethods.efl_input_hold_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),val);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary>The time at which an event was generated.
    /// If the event is generated by a server (eg. X.org or Wayland), then the time may be set by the server. Usually this time will be based on the monotonic clock, if available, but this class can not guarantee it.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns>Time in milliseconds when the event happened.</returns>
    public virtual double GetTimestamp() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_timestamp_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary>Call this when generating events manually.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <param name="ms">Time in milliseconds when the event happened.</param>
    public virtual void SetTimestamp(double ms) {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_timestamp_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),ms);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary>Input device that originated this event.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns>Input device origin</returns>
    public virtual UIKit.Input.Device GetDevice() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_device_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary>Input device that originated this event.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <param name="dev">Input device origin</param>
    public virtual void SetDevice(UIKit.Input.Device dev) {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_device_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),dev);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary>Extra flags for this event, may be changed by the user.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns>Input event flags</returns>
    public virtual UIKit.Input.Flags GetEventFlags() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_event_flags_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary>Extra flags for this event, may be changed by the user.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <param name="flags">Input event flags</param>
    public virtual void SetEventFlags(UIKit.Input.Flags flags) {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_event_flags_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),flags);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event is on hold.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns><c>true</c> if the event is on hold, <c>false</c> otherwise</returns>
    public virtual bool GetProcessed() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_processed_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event is on hold.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <param name="val"><c>true</c> if the event is on hold, <c>false</c> otherwise</param>
    public virtual void SetProcessed(bool val) {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_processed_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),val);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event happened while scrolling.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns><c>true</c> if the event happened while scrolling, <c>false</c> otherwise</returns>
    public virtual bool GetScrolling() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_scrolling_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event happened while scrolling.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <param name="val"><c>true</c> if the event happened while scrolling, <c>false</c> otherwise</param>
    public virtual void SetScrolling(bool val) {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_scrolling_set_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)),val);
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary><c>true</c> if the event was fake, not triggered by real hardware.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <returns><c>true</c> if the event was not from real hardware, <c>false</c> otherwise</returns>
    public virtual bool GetFake() {
        var _ret_var = UIKit.Input.EventConcrete.NativeMethods.efl_input_fake_get_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        return _ret_var;
    }

    /// <summary>Resets the internal data to 0 or default values.</summary>
    /// <since_tizen> 6 </since_tizen>
    public virtual void Reset() {
        UIKit.Input.EventConcrete.NativeMethods.efl_input_reset_ptr.Value.Delegate((IsGeneratedBindingClass ? this.NativeHandle : UIKit.Wrapper.Globals.efl_super(this.NativeHandle, this.NativeClass)));
        UIKit.DataTypes.Error.RaiseIfUnhandledException();
        
    }

    /// <summary>Property to show if inputs are now on hold.</summary>
    /// <value><c>true</c> if inputs are on hold, <c>false</c> otherwise</value>
    public bool InputHold {
        get { return GetInputHold(); }
        set { SetInputHold(value); }
    }

    /// <summary>The time at which an event was generated.
    /// If the event is generated by a server (eg. X.org or Wayland), then the time may be set by the server. Usually this time will be based on the monotonic clock, if available, but this class can not guarantee it.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value>Time in milliseconds when the event happened.</value>
    public double Timestamp {
        get { return GetTimestamp(); }
        set { SetTimestamp(value); }
    }

    /// <summary>Input device that originated this event.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value>Input device origin</value>
    public UIKit.Input.Device Device {
        get { return GetDevice(); }
        set { SetDevice(value); }
    }

    /// <summary>Extra flags for this event, may be changed by the user.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value>Input event flags</value>
    public UIKit.Input.Flags EventFlags {
        get { return GetEventFlags(); }
        set { SetEventFlags(value); }
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event is on hold.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value><c>true</c> if the event is on hold, <c>false</c> otherwise</value>
    public bool Processed {
        get { return GetProcessed(); }
        set { SetProcessed(value); }
    }

    /// <summary><c>true</c> if <see cref="UIKit.Input.IEvent.EventFlags"/> indicates the event happened while scrolling.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value><c>true</c> if the event happened while scrolling, <c>false</c> otherwise</value>
    public bool Scrolling {
        get { return GetScrolling(); }
        set { SetScrolling(value); }
    }

    /// <summary><c>true</c> if the event was fake, not triggered by real hardware.</summary>
    /// <since_tizen> 6 </since_tizen>
    /// <value><c>true</c> if the event was not from real hardware, <c>false</c> otherwise</value>
    public bool Fake {
        get { return GetFake(); }
    }

    private static IntPtr GetUIKitClassStatic()
    {
        return UIKit.Input.Hold.efl_input_hold_class_get();
    }

    /// <summary>Wrapper for native methods and virtual method delegates.
    /// For internal use by generated code only.</summary>
    public new class NativeMethods : UIKit.Object.NativeMethods
    {
        private static UIKit.Wrapper.NativeModule Module = new UIKit.Wrapper.NativeModule(UIKit.Libs.Evas);

        /// <summary>Gets the list of Eo operations to override.</summary>
        /// <returns>The list of Eo operations to be overload.</returns>
        public override System.Collections.Generic.List<UIKit_Op_Description> GetEoOps(System.Type type, bool includeInherited)
        {
            var descs = new System.Collections.Generic.List<UIKit_Op_Description>();
            var methods = UIKit.Wrapper.Globals.GetUserMethods(type);

            if (efl_input_hold_get_static_delegate == null)
            {
                efl_input_hold_get_static_delegate = new efl_input_hold_get_delegate(input_hold_get);
            }

            if (methods.FirstOrDefault(m => m.Name == "GetInputHold") != null)
            {
                descs.Add(new UIKit_Op_Description() {api_func = UIKit.Wrapper.FunctionInterop.LoadFunctionPointer(Module.Module, "efl_input_hold_get"), func = Marshal.GetFunctionPointerForDelegate(efl_input_hold_get_static_delegate) });
            }

            if (efl_input_hold_set_static_delegate == null)
            {
                efl_input_hold_set_static_delegate = new efl_input_hold_set_delegate(input_hold_set);
            }

            if (methods.FirstOrDefault(m => m.Name == "SetInputHold") != null)
            {
                descs.Add(new UIKit_Op_Description() {api_func = UIKit.Wrapper.FunctionInterop.LoadFunctionPointer(Module.Module, "efl_input_hold_set"), func = Marshal.GetFunctionPointerForDelegate(efl_input_hold_set_static_delegate) });
            }

            if (includeInherited)
            {
                var all_interfaces = type.GetInterfaces();
                foreach (var iface in all_interfaces)
                {
                    var moredescs = ((UIKit.Wrapper.NativeClass)iface.GetCustomAttributes(false)?.FirstOrDefault(attr => attr is UIKit.Wrapper.NativeClass))?.GetEoOps(type, false);
                    if (moredescs != null)
                        descs.AddRange(moredescs);
                }
            }
            descs.AddRange(base.GetEoOps(type, false));
            return descs;
        }

        /// <summary>Returns the Eo class for the native methods of this class.</summary>
        /// <returns>The native class pointer.</returns>
        public override IntPtr GetUIKitClass()
        {
            return UIKit.Input.Hold.efl_input_hold_class_get();
        }

        #pragma warning disable CA1707, CS1591, SA1300, SA1600

        [return: MarshalAs(UnmanagedType.U1)]
        private delegate bool efl_input_hold_get_delegate(System.IntPtr obj, System.IntPtr pd);

        [return: MarshalAs(UnmanagedType.U1)]
        public delegate bool efl_input_hold_get_api_delegate(System.IntPtr obj);

        public static UIKit.Wrapper.FunctionWrapper<efl_input_hold_get_api_delegate> efl_input_hold_get_ptr = new UIKit.Wrapper.FunctionWrapper<efl_input_hold_get_api_delegate>(Module, "efl_input_hold_get");

        private static bool input_hold_get(System.IntPtr obj, System.IntPtr pd)
        {
            UIKit.DataTypes.Log.Debug("function efl_input_hold_get was called");
            var ws = UIKit.Wrapper.Globals.GetWrapperSupervisor(obj);
            if (ws != null)
            {
                bool _ret_var = default(bool);
                try
                {
                    _ret_var = ((Hold)ws.Target).GetInputHold();
                }
                catch (Exception e)
                {
                    UIKit.DataTypes.Log.Warning($"Callback error: {e.ToString()}");
                    UIKit.DataTypes.Error.Set(UIKit.DataTypes.Error.UNHANDLED_EXCEPTION);
                }

                return _ret_var;
            }
            else
            {
                return efl_input_hold_get_ptr.Value.Delegate(UIKit.Wrapper.Globals.efl_super(obj, UIKit.Wrapper.Globals.efl_class_get(obj)));
            }
        }

        private static efl_input_hold_get_delegate efl_input_hold_get_static_delegate;

        
        private delegate void efl_input_hold_set_delegate(System.IntPtr obj, System.IntPtr pd, [MarshalAs(UnmanagedType.U1)] bool val);

        
        public delegate void efl_input_hold_set_api_delegate(System.IntPtr obj, [MarshalAs(UnmanagedType.U1)] bool val);

        public static UIKit.Wrapper.FunctionWrapper<efl_input_hold_set_api_delegate> efl_input_hold_set_ptr = new UIKit.Wrapper.FunctionWrapper<efl_input_hold_set_api_delegate>(Module, "efl_input_hold_set");

        private static void input_hold_set(System.IntPtr obj, System.IntPtr pd, bool val)
        {
            UIKit.DataTypes.Log.Debug("function efl_input_hold_set was called");
            var ws = UIKit.Wrapper.Globals.GetWrapperSupervisor(obj);
            if (ws != null)
            {
                
                try
                {
                    ((Hold)ws.Target).SetInputHold(val);
                }
                catch (Exception e)
                {
                    UIKit.DataTypes.Log.Warning($"Callback error: {e.ToString()}");
                    UIKit.DataTypes.Error.Set(UIKit.DataTypes.Error.UNHANDLED_EXCEPTION);
                }

                
            }
            else
            {
                efl_input_hold_set_ptr.Value.Delegate(UIKit.Wrapper.Globals.efl_super(obj, UIKit.Wrapper.Globals.efl_class_get(obj)), val);
            }
        }

        private static efl_input_hold_set_delegate efl_input_hold_set_static_delegate;

        #pragma warning restore CA1707, CS1591, SA1300, SA1600

}
}
}
}

#if EFL_BETA
#pragma warning disable CS1591
public static class UIKit_InputHold_ExtensionMethods {
}
#pragma warning restore CS1591
#endif
