name: Build

on:
  pull_request:
    branches:
    - master
    - API*

  push:
    branches:
    - master
    - API*
    paths:
    - 'build/**'
    - 'internals/**'
    - 'src/**'
    - 'tools/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: getChangedFiles
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: TizenAPI/tizenfx-build-actions/problem-filter@v1
      with:
        run: ./build.sh full /p:BuildWithAnalyzer=True
        files: ${{ steps.getChangedFiles.outputs.all }}
