name: Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build (Pull Request)
      if: ${{ github.event_name == 'pull_request' }}
      run: ./build.sh full /p:BuildWithAnalyzer=True
    
    - name: Build (Push)
      if: ${{ github.event_name == 'push' }}
      run: ./build.sh full
    
    - name: Pack
      run: ./build.sh pack
