name: "Deploy Documents"

on:
  workflow_dispatch:

jobs:

  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: TizenAPI/TizenFX-Docs
        ref: net8.0

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX Tool
      run: dotnet tool install -g docfx --version 2.78.4

    - name: Get Repository Info
      id: info
      run: |
        COMMIT=$(git ls-remote https://github.com/Samsung/TizenFX.git refs/heads/main | cut -f1)
        echo "commit=$COMMIT" >> $GITHUB_OUTPUT

    - name: Cache Build
      id: cache-v
      uses: actions/cache@v4
      with:
        path: |
          _site
          obj
        key: docfx-site-v4-${{ steps.info.outputs.commit }}-${{ hashFiles('docfx.json', 'filterConfig.yml') }}

    - name: Build All Versions
      if: steps.cache-v.outputs.cache-hit != 'true'
      run: |
        chmod +x ./build.sh
        # Clone all versions
        ./build.sh clone
        ./build.sh restore
        ./build.sh build
        ./build.sh build internals

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: site-full
        path: |
          _site/

  deploy:
    needs: [build-docs]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: TizenAPI/TizenFX-Docs
        ref: net8.0

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: site-full
        path: _site

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies for Indexing19
      run: |
        npm install JSONStream lunr

    - name: Generate Search Index
      run: |
        chmod +x ./build.sh
        ./build.sh index

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
        user_name: 'TizenAPI-Bot'
        user_email: 'tizenapi@samsung.com'
        full_commit_message: 'Update documents (Matrix Build)'